apiVersion: v1
kind: Service
metadata:
  name: detection-service
  namespace: helios-prod
  labels:
    app: detection
spec:
  type: ClusterIP
  selector:
    app: detection
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: metrics
      protocol: TCP
      port: 8003
      targetPort: 8003
