apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: helios-prod
  labels:
    app: ingestion
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: ingestion
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: metrics
      protocol: TCP
      port: 8081
      targetPort: 8081
  sessionAffinity: None
