apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting
  namespace: helios-prod
  labels:
    app: reporting
    component: genai
    phase: "3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
        component: genai
        phase: "3"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8004"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: reporting
          image: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/helios-reporting:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8002
              protocol: TCP
            - name: metrics
              containerPort: 8004
              protocol: TCP
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: helios-config
                  key: KAFKA_BROKERS
            - name: KAFKA_ALERTS_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: helios-config
                  key: KAFKA_ALERTS_TOPIC
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: helios-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: helios-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: helios-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: helios-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: helios-secrets
                  key: DB_PASSWORD
            - name: REPORT_GENERATOR_MODE
              valueFrom:
                configMapKeyRef:
                  name: helios-config
                  key: REPORT_GENERATOR_MODE
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: helios-secrets
                  key: ANTHROPIC_API_KEY
            - name: CLAUDE_MODEL
              valueFrom:
                configMapKeyRef:
                  name: helios-config
                  key: CLAUDE_MODEL
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: helios-config
                  key: LOG_LEVEL
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: reports
              mountPath: /app/reports
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: reports
          emptyDir: {}
      restartPolicy: Always
